### ISSUE TITLE
different crash when starting in production

### ISSUE THREAD

**Issue by Aaronstar-McClure** [ATLauncher/Discord-Bot#14]
> @atlauncher/discord-bot@0.1.0 start /var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be
> node dist

unhandledRejection Error: An invalid token was provided.
    at Promise (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/rest/RESTMethods.js:33:44)
    at Promise (<anonymous>)
    at RESTMethods.login (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/rest/RESTMethods.js:32:12)
    at Client.login (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/Client.js:277:30)
    at Bot.start (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/Bot.js:75:24)
    at Object.<anonymous> (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/index.js:11:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12) Promise {
  <rejected> Error: An invalid token was provided.
    at Promise (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/rest/RESTMethods.js:33:44)
    at Promise (<anonymous>)
    at RESTMethods.login (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/rest/RESTMethods.js:32:12)
    at Client.login (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/node_modules/discord.js/src/client/Client.js:277:30)
    at Bot.start (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/Bot.js:75:24)
    at Object.<anonymous> (/var/lib/pufferd/servers/7a03dcb9-6b0d-4585-8bea-b7f88d1ba4be/dist/index.js:11:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12) }

**Comment by Aaronstar-McClure** [comment]
$ sudo npm -v
5.3.0
$ node -v
v8.6.0

**Comment by Aaronstar-McClure** [comment]
and yes, it is the correct token, i tried twice

**Comment by Aaronstar-McClure** [comment]
nevermind, json error later in config file
